# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JyaLStXquxSgVUjtcmzKVConcss_8ECE
"""

import pandas as pd
import matplotlib.pyplot as plt
Tree=pd.read_csv('./Tree.csv')

ll=[]

for i in range(len(Tree)):
	#print(i)
	x=[Tree.x1.values[i],Tree.x2.values[i]]
	y=[Tree.y1.values[i],Tree.y2.values[i]]
	#print(x)
	#print(y)
	plt.plot(x,y,color='black')
	# for i_x, i_y in zip(x, y):

	# 	if((i_x,i_y)) not in ll:
	# 		print("(i_x,i_y):- ",(i_x,i_y))
	# 		plt.text(i_x, i_y, '({}, {})'.format(i_x, i_y))
	# 		ll.append((i_x,i_y))

#plt.show() 
plt.savefig('graph.png') 