# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JyaLStXquxSgVUjtcmzKVConcss_8ECE
"""

import pandas as pd
import matplotlib.pyplot as plt
import sys
import subprocess

# input_file=sys.argv[1]
# subprocess.call("python3 straighten.py "+input_file,shell=True)

Tree=pd.read_csv('Tree.csv')
with open("input","r") as fp:
	lines=fp.readlines()
	c1=0
	c2=0

	xx=[]
	yy=[]

	for i in range(1,len(lines)):
	  ll=lines[i].split()
	  xx.append(int(ll[0]))
	  yy.append(int(ll[1]))
	  
	  c1+=1

	print(xx)
	print(yy) 
	print(len(xx)) 

	plt.scatter(xx,yy,color='black')
	  
	for i in range(len(Tree)):
	  x=[Tree.x1.values[i],Tree.x2.values[i]]
	  y=[Tree.y1.values[i],Tree.y2.values[i]]
	  plt.plot(x,y,color='black')
	  print(x)
	  print(y)
	  print("")
	  c2+=1

	print("c1: ",c1)
	print("c2: ",c2)


plt.show()
